name: spotwatch
description: "A minimal, mobile, reverse beacon client"


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  reverse_beacon: 1.0.5
  get_it: ^7.7.0
  connectivity_plus: ^6.0.2
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  html: ^0.15.4
  gridlocator: ^0.0.3
  http: ^1.2.1
  intl: ^0.19.0
  wakelock: ^0.6.2
  package_info_plus: ^8.0.0

dependency_overrides:
  win32: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  connectivity_plus_platform_interface: any
  mockito: ^5.4.4
  build_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image:  "assets/splash.png"

  android_12:
    color: "#ffffff"
    image:  "assets/splash.png"


  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
