name: "Build & Release"
on:
    pull_request:
        branches:
            - main
            - master
    push:
        branches:
            - main
            - master
            - develop

jobs:
    build-and-release-linux:
        name: Build & Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: '17.0.7'
            - uses: subosito/flutter-action@v1
              with:
                  flutter-version: '3.1'
            - run: flutter pub get
            - run: flutter analyze
            - run: flutter test
            - run: flutter build apk --debug --split-per-abi
            - uses: ncipollo/release-action@v1
              with:
                artifacts: "build/app/output/apk/debug/*"
                tag: v1.0.${{github.run_number}}
                token: ${{ secrets.TOKEN }}
    build-and-release-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: subosito/flutter-action@v1
              with:
                channel: 'stable'
                flutter-version: '3.1'
            - name: Install project dependencies
              run: flutter pub get
            - name: Generate intermediates
              run: flutter pub run build_runner build --delete-conflicting-outputs
            - name: Enable windows build
              run: flutter config --enable-windows-desktop
            - name: Build artifacts
              run: flutter build windows --release
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: MacRecoveryX-${{github.ref_name}}-windows.zip
                directory: build/windows/runner/Release
            - name: Windows Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files: build/windows/runner/Release/MacRecoveryX-${{github.ref_name}}-windows.zip
    
    build-and-release-macos:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2
            - uses: subosito/flutter-action@v1
              with:
                channel: 'stable'
                flutter-version: '3.1'
            - name: Install project dependencies
              run: flutter pub get
            - name: Generate intermediates
              run: flutter pub run build_runner build --delete-conflicting-outputs
            - name: Enable macOS build
              run: flutter config --enable-macos-desktop
            - name: Build artifacts
              run: flutter build macos --release
            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                type: 'zip'
                filename: MacRecoveryX-${{github.ref_name}}-macos.zip
                directory: build/macos/Build/Products/Release
            - name: macOS Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                files: build/macos/Build/Products/Release/MacRecoveryX-${{github.ref_name}}-macos.zip

